### ISSUE TITLE
Deprecated library in sample

### ISSUE THREAD

**Issue by tarepan** [aws-samples/amazon-sagemaker-managed-spot-training#1]
## Summary
The sample use `sagemaker_containers`, which is already deprecated.  

## Detail
Sample "amazon-sagemaker-managed-spot-training" use `sagemaker_containers`.  
https://github.com/aws-samples/amazon-sagemaker-managed-spot-training/blob/3fdf4d30f980e3faa76d8ecba3cc3e271121a5a3/pytorch_managed_spot_training_checkpointing/source_dir/cifar10.py#L3

The library is already deprecated.  

> WARNING: This package has been deprecated.  
> [ref](https://github.com/aws/sagemaker-containers/blob/master/README.rst)  

Using ` SageMaker Inference Toolkit` maybe better.

**Comment by eitansela** [comment]
Hello @tarepan 
Thanks for the feedback.
I will fix it in the following days.

**Comment by eitansela** [comment]
Issue fixed with [latest commit](https://github.com/aws-samples/amazon-sagemaker-managed-spot-training/commit/89de1306c3e3ca60bcaa7e492012ff18e8d72485) - Upgraded PyTorch version to 1.6.0 and stopped using deprecated sagemaker_containers package.

**Comment by eitansela** [comment]
Issue fixed with [latest commit](https://github.com/aws-samples/amazon-sagemaker-managed-spot-training/commit/89de1306c3e3ca60bcaa7e492012ff18e8d72485) - Upgraded PyTorch version to 1.6.0 and stopped using deprecated sagemaker_containers package.
